In [2]:
import tensorflow as tf
import numpy as np

In [15]:
matrix1 = tf.constant([[1., 2.], [3., 4.]])
matrix2 = tf.constant([[1.], [2.]])
print("Matrix 1 shape", matrix1.shape)
print("Matrix 2 shape", matrix2.shape)
tf.matmul(matrix1, matrix2).eval()


Matrix 1 shape (2, 2)
Matrix 2 shape (2, 1)


array([[ 5.],
       [11.]], dtype=float32)

In [7]:
interactive_sess = tf.InteractiveSession()



### Broadcasting

In [17]:
matrix1 = tf.constant([[1., 2.]])
matrix2 = tf.constant(3.)
(matrix1 + matrix2).eval()

array([[4., 5.]], dtype=float32)

In [18]:
matrix1 = tf.constant([[1., 2.]])
matrix2 = tf.constant([3., 4.])
(matrix1 + matrix2).eval()

array([[4., 6.]], dtype=float32)

In [19]:
matrix1 = tf.constant([[1., 2.]])
matrix2 = tf.constant([[3.], [4.]])
(matrix1 + matrix2).eval()

array([[4., 5.],
       [5., 6.]], dtype=float32)

### Reduce mean

In [20]:
tf.reduce_mean([1, 2], axis=0).eval()

1

In [21]:
x = [[1., 2.],
     [3., 4.]]

tf.reduce_mean(x).eval()

2.5

In [22]:
tf.reduce_mean(x, axis=0).eval()

array([2., 3.], dtype=float32)

In [23]:
tf.reduce_mean(x, axis=1).eval()

array([1.5, 3.5], dtype=float32)

In [24]:
tf.reduce_mean(x, axis=-1).eval()

array([1.5, 3.5], dtype=float32)

### Reduce sum

In [25]:
x = [[1., 2.],
     [3., 4.]]

In [26]:
tf.reduce_sum(x).eval()

10.0

In [27]:
tf.reduce_sum(x, axis=0).eval()

array([4., 6.], dtype=float32)

In [28]:
tf.reduce_sum(x, axis=1).eval()

array([3., 7.], dtype=float32)

In [29]:
tf.reduce_sum(x, axis=-1).eval()

array([3., 7.], dtype=float32)

In [32]:
tf.reduce_mean(tf.reduce_sum(x, axis=-1)).eval()

5.0

### Argmax

In [11]:
x = [[0, 1, 2],
     [2, 1, 0]]
tf.argmax(x, axis=0).eval()

array([1, 0, 0])

In [9]:
tf.argmax(x, 1).eval()

array([2, 0])

In [35]:
tf.argmax(x, axis=-1).eval()

array([2, 0])

### Reshape

In [46]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
               
               [[6, 7, 8],
                [9, 10, 11]]])
t.shape

(2, 2, 3)

In [47]:
tf.reshape(t, shape=[-1, 3]).eval()

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [57]:
tf.reshape(t, shape=[-1, 1, 3]).eval()

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

### Reshape(squeeze, expand)

In [58]:
tf.squeeze([[0], [1], [2]]).eval()

array([0, 1, 2], dtype=int32)

In [60]:
tf.expand_dims([0, 1, 2], 1).eval()

array([[0],
       [1],
       [2]], dtype=int32)

In [20]:
# 차원이 하나 자동으로 생김
tf.one_hot([[0], [1], [3], [0]], depth=3).eval()

array([[[1., 0., 0.]],

       [[0., 1., 0.]],

       [[0., 0., 0.]],

       [[1., 0., 0.]]], dtype=float32)

In [18]:
t = tf.one_hot([[0], [1], [2], [0]], depth=3).eval()
# 차원을 하나 줄여주기 위해서는 reshape을 다시 해야함
tf.reshape(t, shape=[-1, 3]).eval()


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

### Casting

In [92]:
tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).eval()

array([1, 2, 3, 4], dtype=int32)

In [94]:
tf.cast([True, False, 1 == 1, 0 == 1], tf.int32).eval()

array([1, 0, 1, 0], dtype=int32)

### Stack

In [95]:
x = [1, 4]
y = [2, 5]
z = [3, 6]

# Pack along first dim.
tf.stack([x, y, z]).eval()

array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)

In [100]:
tf.stack([x, y, z], axis=1).eval()

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

### Ones and Zeros like

In [104]:
x = [[0, 1, 2],
     [2, 1, 0]]

tf.ones_like(x).eval()

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [102]:
tf.zeros_like(x).eval()

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

### Zip

In [105]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


In [107]:
for x, y in enumerate([1, 2, 3]):
    print(x, y)

0 1
1 2
2 3
