In [1]:
import tensorflow as tf

In [2]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

# placeholders for a tensor that will be always fed.
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))
# Minimize. Need a very small Learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                          feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, hy_val, "\nPrediction:\n", hy_val)

0 Cost:  2499.3767 [108.345535 130.57127  128.74956  138.58179  100.70563 ] 
Prediction:
 [108.345535 130.57127  128.74956  138.58179  100.70563 ]
10 Cost:  0.7838893 [152.56139 183.72054 181.11575 195.60771 141.24603] 
Prediction:
 [152.56139 183.72054 181.11575 195.60771 141.24603]
20 Cost:  0.75846875 [152.69244 183.88318 181.27335 195.77975 141.37099] 
Prediction:
 [152.69244 183.88318 181.27335 195.77975 141.37099]
30 Cost:  0.75593555 [152.69014 183.8855  181.27298 195.7798  141.37366] 
Prediction:
 [152.69014 183.8855  181.27298 195.7798  141.37366]
40 Cost:  0.7534064 [152.68745 183.88734 181.27214 195.77934 141.37598] 
Prediction:
 [152.68745 183.88734 181.27214 195.77934 141.37598]
50 Cost:  0.75091136 [152.68475 183.88916 181.2713  195.77885 141.37823] 
Prediction:
 [152.68475 183.88916 181.2713  195.77885 141.37823]
60 Cost:  0.74842227 [152.68208 183.89098 181.27046 195.77838 141.38052] 
Prediction:
 [152.68208 183.89098 181.27046 195.77838 141.38052]
70 Cost:  0.74592495 

660 Cost:  0.62064236 [152.5335  183.99205 181.22386 195.75272 141.5064 ] 
Prediction:
 [152.5335  183.99205 181.22386 195.75272 141.5064 ]
670 Cost:  0.6188408 [152.53122 183.99359 181.22314 195.75235 141.50833] 
Prediction:
 [152.53122 183.99359 181.22314 195.75235 141.50833]
680 Cost:  0.6170436 [152.52893 183.99515 181.22243 195.75195 141.51024] 
Prediction:
 [152.52893 183.99515 181.22243 195.75195 141.51024]
690 Cost:  0.6152682 [152.52667 183.99669 181.22173 195.75156 141.51216] 
Prediction:
 [152.52667 183.99669 181.22173 195.75156 141.51216]
700 Cost:  0.61349297 [152.5244  183.99821 181.22101 195.75119 141.51407] 
Prediction:
 [152.5244  183.99821 181.22101 195.75119 141.51407]
710 Cost:  0.6117345 [152.52214 183.99976 181.2203  195.75078 141.51596] 
Prediction:
 [152.52214 183.99976 181.2203  195.75078 141.51596]
720 Cost:  0.6099718 [152.5199  184.0013  181.2196  195.75043 141.51788] 
Prediction:
 [152.5199  184.0013  181.2196  195.75043 141.51788]
730 Cost:  0.60823494 [15

1360 Cost:  0.5149701 [152.38747 184.09122 181.1779  195.72868 141.62883] 
Prediction:
 [152.38747 184.09122 181.1779  195.72868 141.62883]
1370 Cost:  0.5137241 [152.38557 184.09253 181.17732 195.7284  141.63042] 
Prediction:
 [152.38557 184.09253 181.17732 195.7284  141.63042]
1380 Cost:  0.5124852 [152.38367 184.0938  181.17671 195.72809 141.63199] 
Prediction:
 [152.38367 184.0938  181.17671 195.72809 141.63199]
1390 Cost:  0.5112504 [152.38179 184.0951  181.17612 195.72778 141.63356] 
Prediction:
 [152.38179 184.0951  181.17612 195.72778 141.63356]
1400 Cost:  0.510026 [152.37991 184.09637 181.17554 195.72751 141.63515] 
Prediction:
 [152.37991 184.09637 181.17554 195.72751 141.63515]
1410 Cost:  0.5088126 [152.37804 184.09764 181.17494 195.72719 141.6367 ] 
Prediction:
 [152.37804 184.09764 181.17494 195.72719 141.6367 ]
1420 Cost:  0.5075934 [152.37614 184.0989  181.17433 195.72688 141.63824] 
Prediction:
 [152.37614 184.0989  181.17433 195.72688 141.63824]
1430 Cost:  0.5064008

### Using Matrix

In [9]:
x_data = [[73., 80., 75.], [93., 88., 93.],
         [89., 91., 90.], [ 96., 98., 100.], [73., 66., 70.]]
y_data = [[152.], [185.], [180.], [196.], [142.]]

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight1')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))
# Minimize. Need a very small Learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph
sess.run(tf.global_variables_initializer())
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, hy_val, "\nPrediction:\n", hy_val)

0 Cost:  106921.05 [[-136.79137]
 [-165.06099]
 [-161.9537 ]
 [-180.16747]
 [-123.0052 ]] 
Prediction:
 [[-136.79137]
 [-165.06099]
 [-161.9537 ]
 [-180.16747]
 [-123.0052 ]]
10 Cost:  3.2283072 [[152.46251]
 [182.60408]
 [180.60477]
 [192.87102]
 [142.17583]] 
Prediction:
 [[152.46251]
 [182.60408]
 [180.60477]
 [192.87102]
 [142.17583]]
20 Cost:  2.2476368 [[153.33582]
 [183.65726]
 [181.64058]
 [193.99992]
 [142.9793 ]] 
Prediction:
 [[153.33582]
 [183.65726]
 [181.64058]
 [193.99992]
 [142.9793 ]]
30 Cost:  2.245792 [[153.33653]
 [183.66167]
 [181.64304]
 [194.00348]
 [142.98277]] 
Prediction:
 [[153.33653]
 [183.66167]
 [181.64304]
 [194.00348]
 [142.98277]]
40 Cost:  2.2439506 [[153.33464]
 [183.66292]
 [181.64236]
 [194.00365]
 [142.98383]] 
Prediction:
 [[153.33464]
 [183.66292]
 [181.64236]
 [194.00365]
 [142.98383]]
50 Cost:  2.2421215 [[153.33276]
 [183.66417]
 [181.64172]
 [194.00386]
 [142.98492]] 
Prediction:
 [[153.33276]
 [183.66417]
 [181.64172]
 [194.00386]
 [142.9849

800 Cost:  2.1186748 [[153.20245]
 [183.74855]
 [181.59547]
 [194.01917]
 [143.05457]] 
Prediction:
 [[153.20245]
 [183.74855]
 [181.59547]
 [194.01917]
 [143.05457]]
810 Cost:  2.1172087 [[153.20088]
 [183.74959]
 [181.5949 ]
 [194.01938]
 [143.05539]] 
Prediction:
 [[153.20088]
 [183.74959]
 [181.5949 ]
 [194.01938]
 [143.05539]]
820 Cost:  2.1157253 [[153.19928]
 [183.75061]
 [181.59435]
 [194.0196 ]
 [143.05617]] 
Prediction:
 [[153.19928]
 [183.75061]
 [181.59435]
 [194.0196 ]
 [143.05617]]
830 Cost:  2.1142406 [[153.19768]
 [183.75163]
 [181.59378]
 [194.01984]
 [143.05696]] 
Prediction:
 [[153.19768]
 [183.75163]
 [181.59378]
 [194.01984]
 [143.05696]]
840 Cost:  2.1127656 [[153.19612]
 [183.75264]
 [181.5932 ]
 [194.02008]
 [143.05775]] 
Prediction:
 [[153.19612]
 [183.75264]
 [181.5932 ]
 [194.02008]
 [143.05775]]
850 Cost:  2.1113064 [[153.19455]
 [183.75365]
 [181.59264]
 [194.02031]
 [143.05855]] 
Prediction:
 [[153.19455]
 [183.75365]
 [181.59264]
 [194.02031]
 [143.05855]

1650 Cost:  2.0038838 [[153.07909]
 [183.82767]
 [181.55066]
 [194.04092]
 [143.1127 ]] 
Prediction:
 [[153.07909]
 [183.82767]
 [181.55066]
 [194.04092]
 [143.1127 ]]
1660 Cost:  2.002623 [[153.07774]
 [183.82849]
 [181.55016]
 [194.04121]
 [143.11325]] 
Prediction:
 [[153.07774]
 [183.82849]
 [181.55016]
 [194.04121]
 [143.11325]]
1670 Cost:  2.0014186 [[153.07645]
 [183.82933]
 [181.5497 ]
 [194.0415 ]
 [143.11383]] 
Prediction:
 [[153.07645]
 [183.82933]
 [181.5497 ]
 [194.0415 ]
 [143.11383]]
1680 Cost:  2.0001893 [[153.07515]
 [183.83018]
 [181.54921]
 [194.0418 ]
 [143.11441]] 
Prediction:
 [[153.07515]
 [183.83018]
 [181.54921]
 [194.0418 ]
 [143.11441]]
1690 Cost:  1.9989796 [[153.07382]
 [183.831  ]
 [181.54872]
 [194.04205]
 [143.11496]] 
Prediction:
 [[153.07382]
 [183.831  ]
 [181.54872]
 [194.04205]
 [143.11496]]
1700 Cost:  1.9977531 [[153.07251]
 [183.83183]
 [181.54823]
 [194.04234]
 [143.11554]] 
Prediction:
 [[153.07251]
 [183.83183]
 [181.54823]
 [194.04234]
 [143.1